### ISSUE TITLE
quill notarization failed

### ISSUE THREAD

**Issue by andrewhsu** [anchore/quill#118]
Using `quill` 0.2.0 to sign and notarize an arm64 binary and I've been getting HTTP 400 error from the notarization server. Signing and notarization with `quill` has worked without hiccups throughout this year, but last night started getting an error, but it ended up working after retry and no changes to the usage of `quill`.

This morning started getting the error again even after retries:
```
        * notarization failed: unable to start submission: http status="400 Bad Request": body="<HTML><HEAD>\n<TITLE>Bad Request</TITLE>\n</HEAD><BODY>\n<H1>Bad Request</H1>\nYour browser sent a request that this server could not understand.<P>\nReference&#32;&#35;7&#46;4c822c17&#46;1692969095&#46;ec8f4c44\n</BODY>\n</HTML>\n"
```

Is there something that could be done in `quill` to address this or is this an issue on the apple web service for notarization?

**Comment by willmurphyscode** [comment]
Hi @andrewhsu! Thanks for the bug report. We're currently investigating.

**Comment by benr** [comment]
My builds are failing too.

**Comment by wagoodman** [comment]
We are getting a release out in the next few minutes that will address this -- thanks for reporting!

**Comment by wagoodman** [comment]
Released 🎉  https://github.com/anchore/quill/releases/tag/v0.4.1

**Comment by benr** [comment]
Thanks @wagoodman!
